### ISSUE TITLE
Can't tell what is wrong with a message 'The type, and at least one injected field must be passed.'

### ISSUE THREAD

**Issue by vw98075** [jhipster/jhipster-core#125]
Based on a request, I open a ticket for a problem which has been reported before (https://github.com/jhipster/jhipster-core/issues/91). After running the import command, I get the following error:

$ jhipster import-jdl theModelFile.jh 

    Executing jhipster:import-jdl theModelFile.jh
    The jdl is being parsed.
    { name: 'NullPointerException',
    message: 'The type, and at least one injected field must be passed.',
    prototype: 
     Error
       at new buildException (/home/oem/.config/yarn/global/node_modules/jhipster-core/lib/exceptions/exception_factory.js:44:25)
       at new JDLRelationship (/home/oem/.config/yarn/global/node_modules/jhipster-core/lib/core/jdl_relationship.js:19:13)
       at fillAssociations (/home/oem/.config/yarn/global/node_modules/jhipster-core/lib/parser/jdl_parser.js:155:31)
       at Object.parse [as convertToJDL] (/home/oem/.config/yarn/global/node_modules/jhipster-core/lib/parser/jdl_parser.js:41:3)
       at constructor.parseJDL (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/import-jdl/index.js:77:43)
       at Object.<anonymous> (/home/oem/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
       at /home/oem/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
       at /home/oem/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
       at /home/oem/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
       at runCallback (timers.js:651:20) }
    events.js:160
      throw er; // Unhandled 'error' event
      ^

    Error: ERROR! 
    Error while parsing entities from JDL

    at Environment.error (/home/oem/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
    at constructor.error (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1514:18)
    at constructor.parseJDL (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/import-jdl/index.js:86:22)
    at Object.<anonymous> (/home/oem/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/oem/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /home/oem/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /home/oem/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

For the message error, I have not a hint of the error location. It would be better to report a line number. 

JH version 4.5.4

**Comment by MathieuAA** [comment]
Hi, having lines is tricky as I'd have to modify the grammar to make it more complex (I'll try to find a better way).
As for your error, you've declared an invalid relationship. It must have:
  - a type (one to many, etc.),
  - at least one injected field.

For instance, having:
```
relationship whatever {
  EntityA to EntityB
}
```
doesn't work. The correct way is:
```
relationship whatever {
  EntityA{entityBFieldName} to EntityB{entityAFieldName}
}
```

**Comment by abuechler** [comment]
@MathieuAA How is this going to work with unidirectional one-to-one relationships? Is this still the case? The [documentation](http://www.jhipster.tech/managing-relationships/#7) provides such an example:

```
entity Citizen
entity Passport

relationship OneToOne {
  Citizen{passport} to Passport
}
```

**Comment by MathieuAA** [comment]
It should work all the same.

**Comment by digital-nomad17** [comment]
It says in the documentation that all entities have an implicit id generated for them and that it only needs the relationship to be stated. It doesn't mention anything about foreign keys(field injection). 

The need for field injections[explicit foreign keys] should be mentioned in the documentation if it's needed to be imported into a jhipter project.

**Comment by MathieuAA** [comment]
Well, I can't say I disagree but it's kinda logical. Have you ever seen a relationship with no foreign key? :)

**Comment by ruddell** [comment]
@MathieuAA Would it be possible to default to the injected field to the other entity name if not defined?  I've seen several people run into this issue recently and usually that's the solution.

**Comment by MathieuAA** [comment]
@ruddell Yes, I thought about doing that. That actually would be a use case for one thing I will talk about that during the JHConf :)
I'll see if it can be done before the conf so that I can release v3.0.2 for this. If not, it will be for later.
