### ISSUE TITLE
Incorrect Error "Selecting DTOs without services is forbidden"

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#251]
##### **Overview of the issue**
The following JDL throws an error on import due to `service` being required for the `dto` option, but it shouldn't because `service` is applied to `*`.  It works if you specify `service C with serviceClass` instead of using a wildcard.

```
entity C
service * with serviceClass
dto C with mapstruct     
```
```
The JDL is being parsed.
Error: Selecting DTOs without services is forbidden, for entities C.
ERROR! ERROR! Error while parsing applications and entities from the JDL Error: Selecting DTOs without services is forbidden, for entities C.
Error: ERROR! Error while parsing applications and entities from the JDL Error: Selecting DTOs without services is forbidden, for entities C.
    at Environment.error (/Users/ruddell/Contrib/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/Users/ruddell/Contrib/generator-jhipster/generators/generator-base.js:2058:18)
    at module.exports.importJDL (/Users/ruddell/Contrib/generator-jhipster/generators/import-jdl/index.js:116:14)
    at new ImporterGenerator (/Users/ruddell/Contrib/generator-jhipster/generators/import-jdl/index.js:81:38)
    at new module.exports (/Users/ruddell/Contrib/generator-jhipster/generators/import-jdl/index.js:123:9)
    at Environment.instantiate (/Users/ruddell/Contrib/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:408:12)
    at Environment.create (/Users/ruddell/Contrib/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:386:17)
    at Environment.run (/Users/ruddell/Contrib/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:443:28)
    at runYoCommand (/Users/ruddell/Contrib/generator-jhipster/cli/cli.js:63:13)
    at Command.command.allowUnknownOption.description.action (/Users/ruddell/Contrib/generator-jhipster/cli/cli.js:83:13)
```
##### **Motivation for or Use Case**

This should be valid JDL

##### **Reproduce the error**

Use the JDL from above

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

generator-jhipster: master, v5.2.1
jhipster-core: v3.1.0

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Nice catch @ruddell ! I'll find time this week-end to fix it.

**Comment by ruddell** [comment]
@kannery That's unrelated to this issue and not a bug.  If you choose DTOs, you need to enable services https://www.jhipster.tech/using-dtos/

**Comment by kannery** [comment]
I was trying to import old jdl with the new jhipster version. I have corrected my jdl with the service option. Now it works. Thanks
