### ISSUE TITLE
JDL generation no longer accepting istioRoute after 6.0.1 upgrade

### ISSUE THREAD

**Issue by bdealey** [jhipster/jhipster-core#330]
##### **Overview of the issue**
The JDL file worked fine in jhipster 5.8.  This JDL was taken from a jhipster kubernetes demo.
Since upgrading to jhipster 6.0.1, it now gives the following error. Taking out the following two JDL directives will successfully generate the project.
  istio autoInjection
  istionRoute true

But these two are needed.  Again this worked perfectly in jhipster 5.8

❯ jhipster import-jdl jhipster-app.jdl --debug
INFO! Using JHipster version installed globally
INFO! Debug logging is on
DEBUG!  Executing CLI only script
DEBUG!  cmd: import-jdl from ./import-jdl
DEBUG!  args: jhipster-app.jdl, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: import-jdl, _noHelp: false, parent: Object, _description: Create entities from the JDL file passed in argument.
  By default everything is run in parallel. If you like to interact with the console use '--interactive' flag., _argsDescription: undefined, _events: Object, _eventsCount: 1
INFO! Executing import-jdl jhipster-app.jdl
INFO! Options: debug: true, from-cli: true
DEBUG!  JDLProcessor started with jdlFiles: jhipster-app.jdl and options: debug: true, from-cli: true
INFO! The JDL is being parsed.
error: Error message:
	MismatchedTokenException: Expecting --> '}' <-- but found --> 'istionRoute' <--
	at line: 225, column: 3
DEBUG!  Error:
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'istionRoute' <--
	at line: 225, column: 3
ERROR! Error while parsing applications and entities from the JDL SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'istionRoute' <--
	at line: 225, column: 3
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'istionRoute' <--
	at line: 225, column: 3
    at callApiMethod (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/reader/jdl_reader.js:88:11)
    at parse (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/reader/jdl_reader.js:72:10)
    at Object.parseFromFiles (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/reader/jdl_reader.js:41:10)
    at parseFiles (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:82:20)
    at JDLImporter.import (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/jdl/jdl_importer.js:64:30)
    at JDLProcessor.importJDL (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/cli/import-jdl.js:76:41)
    at JDLProcessor.importJDL (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/cli/import-jdl.js:292:38)
    at module.exports (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/cli/import-jdl.js:446:21)
    at Command.command.allowUnknownOption.description.action.args (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/cli/cli.js:72:36)
    at Command.listener (/usr/local/Cellar/jhipster/6.0.1/libexec/lib/node_modules/generator-jhipster/node_modules/commander/index.js:315:8)

##### **JHipster Version(s)**
jhipster 6.0.1

##### **JHipster configuration**
Below is the jhipster info output.  There is no .yo-rc.json as error is seen in the jhipster import-jdl command.
❯ jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/bdealey/git/sts/kubernetes/k8s03-jh601-ms-ist-np-mci
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.21.0

node: v10.14.1

npm: 6.9.0

yeoman: 2.0.5

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

JDL file attached.  Added .txt extension to it to allow it to be attached for this form.

##### **Browsers and Operating System**

OS: MacOS
There is no browser as this error is generated from the command ine

- [X
[jhipster-app.jdl.txt](https://github.com/jhipster/jhipster-core/files/3208388/jhipster-app.jdl.txt)

] Checking this box is mandatory (this is just to show you read everything)

**Comment by bdealey** [comment]
Forgot to mention that the JDL directive of "istioRoute" is still documented on the JDL web page: https://www.jhipster.tech/jdl/

**Comment by deepu105** [comment]
I think its removed in new version. May be docs are not updated yet.
IstioRoutes are generated by default now

**Comment by MathieuAA** [comment]
This is taken care of. Thanks for reporting this
