### ISSUE TITLE
Different validation rules in CLI and JDL-studio

### ISSUE THREAD

**Issue by mmuruev** [jhipster/jhipster-core#462]
I can create an app with baseName gateway-app from CLI but with JDL-studio this is impossible trow error (- is forbidden)  also minor differences with VC-Code

**Comment by MathieuAA** [comment]
I'm gonna review the rules ASAP. Thanks for bringing that up and sorry for the inconvenience!

**Comment by mmuruev** [comment]
```
❯ jh import-jdl jhipster-jdl.jh
INFO! Using JHipster version installed globally
00h00m00s 0/0: : INFO! Executing import-jdl jhipster-jdl.jh
INFO! Options: from-cli: true, inline:
error: Error message:
The baseName property name must match: /^[A-Za-z][A-Za-z0-9_]*$/, got customer-gateway.
at line: 3, column: 14
Error during import-jdl: Error: The baseName property name must match: /^[A-Za-z][A-Za-z0-9_]*$/, got customer-gateway.
at line: 3, column: 14
SyntaxError: Error: The baseName property name must match: /^[A-Za-z][A-Za-z0-9_]*$/, got customer-gateway.
at line: 3, column: 14
at callApiMethod (/home/mf/.nvm/versions/node/v13.12.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:99:11)
at parse (/home/mf/.nvm/versions/node/v13.12.0/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/readers/jdl_reader.js:83:10)
```

 Now JDL studio is ok with this but importer are broken

**Comment by MathieuAA** [comment]
Dashes are forbidden both in this repo and the generator. The issue comes from the JDL studio which isn't up-to-date. The issue should go there

**Comment by MathieuAA** [comment]
Similar to https://github.com/jhipster/jdl-studio/issues/85. I'll try to address this issue today
