### ISSUE TITLE
JDL Studio gulp build fails from version v1.2.3

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/jhipster-core#98]
**Overview of the issue**
Starting from jhipster-core version v1.2.3 JDL Studio `gulp build` fails with error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)
    at parse_error (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1647:9)
    at Object.next_token [as input] (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1912:9)
    at next (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2012:25)
    at eval (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2134:42)
    at eval (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2073:24)
    at block_ (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2353:20)
    at eval (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2326:25)
    at function_ (eval at <anonymous> (c:\projects\kaido-github\jdl-studio\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2331:15)
```
**Reproduce the error**
* fork and clone [JDL Studio](https://github.com/jhipster/jdl-studio)
* in `bower.json` change from
```
"pegjs_parser": "https://raw.githubusercontent.com/jhipster/jhipster-core/v1.1.5/lib/dsl/pegjs_parser.js",
```
to (error occurs with versions 1.2.3 and 1.2.4)
```
"pegjs_parser": "https://raw.githubusercontent.com/jhipster/jhipster-core/v1.2.4/lib/dsl/pegjs_parser.js",
```
hint: can reference to local version, for example if `jhipster-core` and `jdl-studio` are cloned into same parent folder then reference is:
```
"pegjs_parser": "../jhipster-core/lib/dsl/pegjs_parser.js",
```
* `bower install`
* `gulp build`

**Comment by MathieuAA** [comment]
Interesting... I'd rather not have a issue opened here for the JDL Studio though.

**Comment by kaidohallik** [comment]
@MathieuAA Opened jhipster/jdl-studio#27 with additional information.
